/*
Widz 1 do wielu biletow
Bilet 1 do 1 Cena
Bilet 1 do 1 Seans

CREATE TABLE WIDZ(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
	first_name varchar(255) not null,
	last_name varchar(255) not null,
	street varchar(255) not null,
	city varchar(255) not null,
	phone_number varchar(255) not null,
	PRIMARY KEY (id)
);
insert into WIDZ (first_name, last_name,street,city,phone_number) values ('Jarek', 'Nowak','Nowa','Zywiec','111111211');
*/
--1 do wielu biletow
CREATE TABLE KASJER(
id INTEGER GENERATED BY DEFAULT AS IDENTITY,
first_name varchar(255) not null,
last_name varchar(255) not null,
);

INSERT INTO KASJER(first_name,last_name) VALUES('Adam' ,'Nowak');

CREATE TABLE BILET(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  type VARCHAR(255) not null,
  id_kasjer  INTEGER NOT NULL,
  PRIMARY KEY (id),
  FOREIGN key(id_kasjer) REFERENCES KASJER(id) ON UPDATE CASCADE ON DELETE CASCADE
);
--
insert into BILET(id_kasjer,type) VALUES (1,'NORMALNY');
--
--1 cena do 1 biletu WIFE
CREATE TABLE CENA(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_bilet INTEGER NOT NULL,
  koszt DECIMAL,
  PRIMARY KEY(id),
  FOREIGN KEY(id_bilet) REFERENCES BILET(id)
  --CONSTRAINT id_bilet FOREIGN KEY (id_bilet) REFERENCES BILET (`STOCK_ID`)
);

INSERT INTO CENA(id_bilet, koszt)  VALUES (1,122);
--
CREATE TABLE FILM(
id INTEGER GENERATED BY DEFAULT AS IDENTITY,
name varchar(255) not null,
PRIMARY KEY(id)
);

insert into FILM(name) VALUES ('Nowosc');
/*
CREATE TABLE SEANS(
id INTEGER GENERATED BY DEFAULT AS IDENTITY,
--name varchar(255) not null,
id_film INTEGER NOT NULL,
time_seans BIGINT NOT NULL,
PRIMARY KEY (id),
FOREIGN key(id_film) REFERENCES Film(id)
);

INSERT INTO SEANS(id_film,time_seans) values(1,122);
*/




