/*
Widz 1 do wielu biletow
Bilet 1 do 1 Cena
Bilet 1 do 1 Seans
 */
CREATE TABLE WIDZ(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
	first_name varchar(255) not null,
	last_name varchar(255) not null,
	street varchar(255) not null,
	city varchar(255) not null,
	phone_number varchar(255) not null,
	PRIMARY KEY (id)
);

insert into WIDZ (first_name, last_name,street,city,phone_number) values ('Dave', 'Syer','Nowa','Zywiec','111111211');
--1 do Seans
CREATE TABLE BILET(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_widz INTEGER NOT NULL,
  id_seans INTEGER NOT NULL,
  type VARCHAR(255) not null,
  PRIMARY KEY (id),
  FOREIGN key(id_widz) REFERENCES WIDZ(id) ON UPDATE CASCADE ON DELETE CASCADE,
  --FOREIGN key(id_seans) REFERENCES SEANS(id)
);
--
insert into BILET(id_widz,id_seans,type) VALUES (1,1,'NORMALNY');

CREATE TABLE FILM(
id INTEGER GENERATED BY DEFAULT AS IDENTITY,
name varchar(255) not null,
PRIMARY KEY(id)
);

insert into FILM(name) VALUES ('Nowosc');

CREATE TABLE SEANS(
id INTEGER GENERATED BY DEFAULT AS IDENTITY,
--name varchar(255) not null,
id_film INTEGER NOT NULL,
time_seans BIGINT NOT NULL,
PRIMARY KEY (id),
FOREIGN key(id_film) REFERENCES Film(id)
);

INSERT INTO SEANS(id_film,time_seans) values(1,122);
--1 cena do 1 biletu
CREATE TABLE CENA(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_bilet INTEGER NOT NULL,
  koszt DECIMAL
);

INSERT INTO CENA(id_bilet, koszt)  VALUES (1,122);