
CREATE TABLE KASJER(
id INTEGER GENERATED BY DEFAULT AS IDENTITY,
first_name varchar(255) not null,
last_name varchar(255) not null,
);

INSERT INTO KASJER(first_name,last_name) VALUES('Adam' ,'Nowak');

CREATE TABLE BILET(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  type VARCHAR(255) not null,
  id_kasjer  INTEGER NOT NULL,
  PRIMARY KEY (id),
  FOREIGN key(id_kasjer) REFERENCES KASJER(id) ON UPDATE CASCADE ON DELETE CASCADE
);
--
insert into BILET(id_kasjer,type) VALUES (1,'NORMALNY');
--
CREATE TABLE CENA(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_bilet INTEGER NOT NULL,
  koszt DECIMAL,
  PRIMARY KEY(id),
  FOREIGN KEY(id_bilet) REFERENCES BILET(id)  ON UPDATE CASCADE ON DELETE CASCADE
);

INSERT INTO CENA(id_bilet, koszt)  VALUES (1,122);
--
CREATE TABLE FILM(
id INTEGER GENERATED BY DEFAULT AS IDENTITY,
name varchar(255) not null,
PRIMARY KEY(id)
);

insert into FILM(name) VALUES ('Nowosc');

CREATE TABLE SEANS(
id INTEGER GENERATED BY DEFAULT AS IDENTITY,
name varchar(255) not null,
id_bilet INTEGER NOT NULL,
PRIMARY KEY (id),
FOREIGN key(id_bilet) REFERENCES Bilet(id)
);

INSERT INTO SEANS(name,id_bilet) values('Nowy film',1);





